version: '3'
services:
 node-server:
    build: .
    ports:
      - "3000:3000"

 db:
    image: mysql:latest
    container_name: dolphin
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: banana
    networks:
      - dev_network

  # phpmyadmin
 phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: banana 
    networks:
      - dev_network
 adminer:
    # depends_on:
    #   - db
    image: adminer:latest
    container_name: atlas
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8888:8080
    networks:
      - dev_network

networks:
  dev_network:

volumes:
  db_data: